"""added Cyclist model

Revision ID: 30388454e02c
Revises: 611e0dbe22ba
Create Date: 2022-11-07 20:41:31.991212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30388454e02c'
down_revision = '611e0dbe22ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyclist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bike', sa.Column('cyclist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bike', 'cyclist', ['cyclist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_column('bike', 'cyclist_id')
    op.drop_table('cyclist')
    # ### end Alembic commands ###
